#!/bin/bash
#SBATCH --job-name=IME-MAT
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=120G
#SBATCH --time=24:00:00
#SBATCH --array=1-22
#SBATCH -o IME-MAT_%A_%a.out
#SBATCH -e IME-MAT_%A_%a.err

# Dependencies
module load matlab/R2017a
module load samtools

# Input
prefix="$1"
trim="$2"

# Run
getMatrices.sh -c 0 -t "$trim" -q 20 --time_limit 20 -- "$prefix" ${SLURM_ARRAY_TASK_ID} 200
